// import './class/jiegoufuzhi'
import 'babel-polyfill'
// import './class/zhengze'
// import './class/string'
// import './class/number'
// import './class/array'
// import './class/function'
// import './class/obj'
import './class/symbol'